name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # ( Build to ./dist or other directory... )

      - name: Install
        run: cd my-app && yarn install

      - name: Echo
        run: echo "HELLO" && echo "$(pwd)"
      # deploy
      # 빌드
      - name: Build
        run: echo "$(pwd)" && cd my-app && echo "$(pwd)" && echo "$(ls)" && yarn run build

      - name: CheckPWD1
        run: cd my-app && echo "$(pwd)" && echo "$(ls)"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./my-app"
          production-branch: main
          github-token: ${{ secrets.TEST_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
