name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # ( Build to ./dist or other directory... )

      - name: Install
        run: cd my-app && yarn install

      - name: Echo
        run: echo "HELLO" && echo "$(pwd)"
      # deploy
      # 빌드
      - name: Build
        run: echo "$(pwd)" && cd my-app && echo "$(pwd)" && echo "$(ls)" && yarn run build

      - name: CheckPWD
        run: cd my-app && echo "$(pwd)" && echo "$(ls)"

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
